//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartDetail
    {
        public int Id { get; set; }
        public int Productid { get; set; }
        public int Customerid { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Visible { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
