//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paymentdetail
    {
        public int Id { get; set; }
        public int Userid { get; set; }
        public int Productid { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<long> Mobileno { get; set; }
        public Nullable<decimal> Totalamount { get; set; }
        public Nullable<System.DateTime> Orderdate { get; set; }
        public string Paymentmode { get; set; }
    }
}
