//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAprroach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobcategory
    {
        public int Jid { get; set; }
        public int Pid { get; set; }
        public string Jname { get; set; }
        public string Jcompany { get; set; }
        public string Jdescription { get; set; }
        public string Jsalary { get; set; }
        public Nullable<int> Jexperience { get; set; }
        public string Jeducation { get; set; }
        public string Jwebsite { get; set; }
        public string Jaddress { get; set; }
    }
}
