//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAprroach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seeker
    {
        public long Resumeid { get; set; }
        public string Userid { get; set; }
        public Nullable<int> Tenpercent { get; set; }
        public Nullable<int> Twelvepercent { get; set; }
        public Nullable<int> Gradpercent { get; set; }
        public Nullable<int> Postgrad { get; set; }
        public string Jobprofile { get; set; }
        public Nullable<int> Jobex { get; set; }
        public string Resumeurl { get; set; }
    }
}
